//1. Compare Objects for Equivalent Properties
//
//Write a JavaScript program to compare two objects to determine if the first contains equivalent property values to the second one. 

//analysis;
	//compare two objects=>property equivalent



let object1=JSON.parse(process.argv[2]); // we use this to convert the  string that generated by process to argv into object
let object2=JSON.parse(process.argv[3]); //........

function compare_property(obj1,obj2){
	for (let key in obj2){    //here we loop over the obj2 to see whether it's values are equal with obj1 we don't need to make another loop over the obj1 as we are sure they keys are equal just we neeeed to see the values
	   if(obj1[key]!=obj2[key]){
	 	return "Oops,the values of them aren't equal";				
}	
	return "Yep,the values of them are equal";
}	
}
console.log(compare_property(object1,object2));


//note;
// you need to understand how process.argv works;[
//  '/usr/bin/node',        // index 0
//  '/path/problem1.js',    // index 1
//  '{"name":"Ahmed"}',     // index 2
//  '{"name":"Mohae"}'      // index 3
//]
// make sure to wrap the objects you sent throw the terminal in order to escape from removing the douple quotes that shell do if no wrap around it
//also make sure that everything inside the {} of the objects are in douple quotes in order to  check  them else JSON will return error.

